# Generated by Django 3.2 on 2022-01-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='photo',
            field=models.ImageField(default=1, upload_to='about'),
            preserve_default=False,
        ),
    ]
