# Generated by Django 3.2 on 2022-01-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=2000)),
                ('course_name', models.CharField(max_length=2000)),
                ('start', models.DateField()),
                ('End', models.DateField(blank=True, null=True)),
                ('is_present', models.BooleanField(default=False)),
                ('accomplishments', models.JSONField()),
                ('obt_marks', models.CharField(max_length=5)),
            ],
        ),
    ]
